<?php

namespace Database\Seeders;

use App\Models\Ruangan;
use Illuminate\Database\Seeder;

class RuanganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ruangans = [
            ['kode' => 'RG-001', 'nama' => 'ABDUL GANI ABDULLAH'],
            ['kode' => 'RG-002', 'nama' => 'AHMAD JAKA MIRDINATA'],
            ['kode' => 'RG-003', 'nama' => 'ABDUL MANAN'],
            ['kode' => 'RG-004', 'nama' => 'ABDUL MANAF'],
            ['kode' => 'RG-005', 'nama' => 'ABDURRAHMAN'],
            ['kode' => 'RG-006', 'nama' => 'AGUNG SUDRAJAD DIMYATI'],
            ['kode' => 'RG-007', 'nama' => 'AHMAD KAMIL'],
            ['kode' => 'RG-008', 'nama' => 'ASISTEN KAMAR TUN'],
            ['kode' => 'RG-009', 'nama' => 'ANDARI YURIKO SARI'],
            ['kode' => 'RG-010', 'nama' => 'ANDI SANSAN NGANRO'],
            ['kode' => 'RG-011', 'nama' => 'AMRAN SUADI'],
            ['kode' => 'RG-012', 'nama' => 'AGUS SUBROTO'],
            ['kode' => 'RG-013', 'nama' => 'ANGGI'],
            ['kode' => 'RG-014', 'nama' => 'ASKOR TIM E'],
            ['kode' => 'RG-015', 'nama' => 'BOYKE NAPITUPULU'],
            ['kode' => 'RG-016', 'nama' => 'BIAYA PROSES'],
            ['kode' => 'RG-017', 'nama' => 'BONY DANIEL'],
            ['kode' => 'RG-018', 'nama' => 'BUSRA'],
            ['kode' => 'RG-019', 'nama' => 'BUDI NUGROHO'],
            ['kode' => 'RG-020', 'nama' => 'CERAH BANGUN'],
            ['kode' => 'RG-021', 'nama' => 'DJAFNI DJAMAL (TUAKA PERDATA)'],
            ['kode' => 'RG-022', 'nama' => 'DWI SUGIARTO'],
            ['kode' => 'RG-023', 'nama' => 'DWI TJAHYO'],
            ['kode' => 'RG-024', 'nama' => 'DIANA MALEMITA GINTING'],
            ['kode' => 'RG-025', 'nama' => 'EDI RIADI'],
            ['kode' => 'RG-026', 'nama' => 'EKO NUGROHO'],
            ['kode' => 'RG-027', 'nama' => 'ENNID HASANUDDIN'],
            ['kode' => 'RG-028', 'nama' => 'FITRIAMINA'],
            ['kode' => 'RG-029', 'nama' => 'HABIBURRAHMAN'],
            ['kode' => 'RG-030', 'nama' => 'HAKIM ADHOC PHI'],
            ['kode' => 'RG-031', 'nama' => 'HAMDAN'],
            ['kode' => 'RG-032', 'nama' => 'HAMDI'],
            ['kode' => 'RG-033', 'nama' => 'HARY DJATMIKO'],
            ['kode' => 'RG-034', 'nama' => 'HATTA ALI (KMA)'],
            ['kode' => 'RG-035', 'nama' => 'HARI WIDYA'],
            ['kode' => 'RG-036', 'nama' => 'HAKIM TINGGI PEMILAH (PERDATA)'],
            ['kode' => 'RG-037', 'nama' => 'HAKIM TINGGI PEMILAH PERDATA KHUSUS'],
            ['kode' => 'RG-038', 'nama' => 'HAKIM TINGGI PEMILAH PERDATA AGAMA'],
            ['kode' => 'RG-039', 'nama' => 'HASWANDI'],
            ['kode' => 'RG-040', 'nama' => 'HARI SUGIHARTO'],
            ['kode' => 'RG-041', 'nama' => 'HERU PRAMONO'],
            ['kode' => 'RG-042', 'nama' => 'IBRAHIM'],
            ['kode' => 'RG-043', 'nama' => 'I GUSTI AGUNG SUMANATHA'],
            ['kode' => 'RG-044', 'nama' => 'I MADE TARA'],
            ['kode' => 'RG-045', 'nama' => 'IMAM SOEBECHI'],
            ['kode' => 'RG-046', 'nama' => 'IRFAN FACHRUDIN'],
            ['kode' => 'RG-047', 'nama' => 'IS SUDARYONO'],
            ['kode' => 'RG-048', 'nama' => 'IMRON ROSYADI'],
            ['kode' => 'RG-049', 'nama' => 'JARNO BUDIONO'],
            ['kode' => 'RG-050', 'nama' => 'JUNAEDI'],
            ['kode' => 'RG-051', 'nama' => 'KAMAR TUN'],
            ['kode' => 'RG-052', 'nama' => 'KAMAR PERDATA'],
            ['kode' => 'RG-053', 'nama' => 'KASUBBAG KEPEGAWAIAN'],
            ['kode' => 'RG-054', 'nama' => 'KASUBBAG KEUANGAN SEKPAN'],
            ['kode' => 'RG-055', 'nama' => 'KRIS NUGROHO'],
            ['kode' => 'RG-056', 'nama' => 'LUCAS PRAKOSO'],
            ['kode' => 'RG-057', 'nama' => 'LULIK TRI CAHYANINGRUM'],
            ['kode' => 'RG-058', 'nama' => 'LAILATUL AROFAH'],
            ['kode' => 'RG-059', 'nama' => 'MAHDI SOROINDA'],
            ['kode' => 'RG-060', 'nama' => 'MARGONO'],
            ['kode' => 'RG-061', 'nama' => 'MARIA ANNA'],
            ['kode' => 'RG-062', 'nama' => 'MARINA SIDABUTAR'],
            ['kode' => 'RG-063', 'nama' => 'MARIANA SAMIYATI'],
            ['kode' => 'RG-064', 'nama' => 'MUKHTAR ZAMZAMI'],
            ['kode' => 'RG-065', 'nama' => 'MUKTI ARTO'],
            ['kode' => 'RG-066', 'nama' => 'MUHAYAH'],
            ['kode' => 'RG-067', 'nama' => 'NANI INDRAWATI'],
            ['kode' => 'RG-068', 'nama' => 'NURUL ELMIYAH'],
            ['kode' => 'RG-069', 'nama' => 'PANITERA'],
            ['kode' => 'RG-070', 'nama' => 'PANMUD PERDATA'],
            ['kode' => 'RG-071', 'nama' => 'PANMUD PERDATA AGAMA'],
            ['kode' => 'RG-072', 'nama' => 'PANMUD PERDATA KHUSUS'],
            ['kode' => 'RG-073', 'nama' => 'PANMUD TUN'],
            ['kode' => 'RG-074', 'nama' => 'PANJI WIDODO'],
            ['kode' => 'RG-075', 'nama' => 'PARTO HUTOMO'],
            ['kode' => 'RG-076', 'nama' => 'PETUGAS PEMBUAT KOMITMEN'],
            ['kode' => 'RG-077', 'nama' => 'PURWOSUSILO'],
            ['kode' => 'RG-078', 'nama' => 'PANJI WIDAGDO'],
            ['kode' => 'RG-079', 'nama' => 'PRI PAMBUDI TEGUH'],
            ['kode' => 'RG-080', 'nama' => 'PRAYOGA PP KAMAR PERDATA'],
            ['kode' => 'RG-081', 'nama' => 'PP PERDATA'],
            ['kode' => 'RG-082', 'nama' => 'PP ANGGI'],
            ['kode' => 'RG-083', 'nama' => 'RAHMI MULYATI'],
            ['kode' => 'RG-084', 'nama' => 'RUANG E-505'],
            ['kode' => 'RG-085', 'nama' => 'RUANG 803'],
            ['kode' => 'RG-086', 'nama' => 'SLAMET SUPRIYONO PP'],
            ['kode' => 'RG-087', 'nama' => 'SOLTONI MOHDALLY'],
            ['kode' => 'RG-088', 'nama' => 'SUDARYONO'],
            ['kode' => 'RG-089', 'nama' => 'SUDRAJAD DIMYATI'],
            ['kode' => 'RG-090', 'nama' => 'SUNARTO'],
            ['kode' => 'RG-091', 'nama' => 'SUPANDI'],
            ['kode' => 'RG-092', 'nama' => 'SUWARDI'],
            ['kode' => 'RG-093', 'nama' => 'SUGENG SANTOSO'],
            ['kode' => 'RG-094', 'nama' => 'SYAMSUL MAARIF'],
            ['kode' => 'RG-095', 'nama' => 'SYARIFUDIN'],
            ['kode' => 'RG-096', 'nama' => 'SUGIYANTO'],
            ['kode' => 'RG-097', 'nama' => 'SUHARTO'],
            ['kode' => 'RG-098', 'nama' => 'TAKDIR RAHMADI'],
            ['kode' => 'RG-099', 'nama' => 'TUAKA AGAMA'],
            ['kode' => 'RG-100', 'nama' => 'TUAKA PERDATA'],
            ['kode' => 'RG-101', 'nama' => 'TUAKA ULDILAG'],
            ['kode' => 'RG-102', 'nama' => 'TUAKA TUN'],
            ['kode' => 'RG-103', 'nama' => 'TIM E'],
            ['kode' => 'RG-104', 'nama' => 'TIPIKOR'],
            ['kode' => 'RG-105', 'nama' => 'VALERINE'],
            ['kode' => 'RG-106', 'nama' => 'WIDAYATKO SASTROHARDJONO'],
            ['kode' => 'RG-107', 'nama' => 'WKMA'],
            ['kode' => 'RG-108', 'nama' => 'WKMA BIDANG NON YUDISIAL'],
            ['kode' => 'RG-109', 'nama' => 'WKMA BIDANG YUDISIAL'],
            ['kode' => 'RG-110', 'nama' => 'YAKUP GINTING'],
            ['kode' => 'RG-111', 'nama' => 'YOSRAN'],
            ['kode' => 'RG-112', 'nama' => 'YULIUS'],
            ['kode' => 'RG-113', 'nama' => 'YUSTICIA ROZA PUTERI'],
            ['kode' => 'RG-114', 'nama' => 'YUNUS WAHAB'],
            ['kode' => 'RG-115', 'nama' => 'YODI'],
            ['kode' => 'RG-116', 'nama' => 'YASARDIN'],
            ['kode' => 'RG-117', 'nama' => 'ZAHRUL RABAIN'],
        ];

        foreach ($ruangans as $ruangan) {
            Ruangan::create([
                'kode' => $ruangan['kode'],
                'nama' => $ruangan['nama'],
                'deskripsi' => 'Unit kerja di lingkungan Mahkamah Agung',
                'is_active' => true,
            ]);
        }
    }
}
